### ISSUE TITLE
Type error in $min

### ISSUE THREAD

**Issue by quicklisp** [sharplispers/clawk#1]
https://github.com/sharplispers/clawk/blob/f0be2045f4ac496fd09154355929c635f47824d4/clawk.lisp#L1228

```; caught WARNING:
;   The function MIN is called by REDUCE with (STRING T) but it accepts (REAL REAL).
```

Same issue with `$max`

**Comment by luismbo** [comment]
Seems like the fix is to remove these methods and let the default methods perform coercion from strings to numbers.
